export const allAmenities = ["Free Wi-Fi", "Balcony", "Smart TV", "Minibar", "Air Conditioning", "Breakfast Included"];

export const rooms = [
    {
        id: 1,
        name: "Ocean Breeze",
        location: "Alexandria, Egypt",
        type: "Single Room",
        pricePerNight: 80,
        capacity: 1,
        description: "A cozy single room perfect for solo travelers. Includes a comfortable bed and work desk.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-10", checkOut: "2025-11-14" },
        ],
        image: "https://picsum.photos/seed/room1/1024/764",
    },
    {
        id: 2,
        name: "Nile View Suite",
        location: "Cairo, Egypt",
        type: "Deluxe Suite",
        pricePerNight: 150,
        capacity: 2,
        description: "Spacious suite with stunning Nile views and modern amenities for couples.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-05", checkOut: "2025-11-08" },
            { checkIn: "2025-11-20", checkOut: "2025-11-25" },
        ],
        image: "https://picsum.photos/seed/room2/1024/764",
    },
    {
        id: 3,
        name: "Pyramid Panorama",
        location: "Giza, Egypt",
        type: "Double Room",
        pricePerNight: 120,
        capacity: 2,
        description: "Modern double room with views of the pyramids and luxurious bedding.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Balcony"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room3/1024/764",
    },
    {
        id: 4,
        name: "Desert Oasis",
        location: "Hurghada, Egypt",
        type: "Single Room",
        pricePerNight: 75,
        capacity: 1,
        description: "Comfortable single room near the Red Sea with beach access.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Pool Access"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-15", checkOut: "2025-11-18" },
        ],
        image: "https://picsum.photos/seed/room4/1024/764",
    },
    {
        id: 5,
        name: "Luxor Temple View",
        location: "Luxor, Egypt",
        type: "Family Room",
        pricePerNight: 180,
        capacity: 4,
        description: "Spacious family room overlooking ancient temples with two queen beds.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar", "Balcony"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-12", checkOut: "2025-11-16" },
            { checkIn: "2025-11-22", checkOut: "2025-11-27" },
            { checkIn: "2025-12-01", checkOut: "2025-12-05" },
        ],
        image: "https://picsum.photos/seed/room5/1024/764",
    },
    {
        id: 6,
        name: "Mediterranean Retreat",
        location: "Alexandria, Egypt",
        type: "Double Room",
        pricePerNight: 95,
        capacity: 2,
        description: "Elegant double room with Mediterranean decor and sea breeze.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Work Desk"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room6/1024/764",
    },
    {
        id: 7,
        name: "Citadel Comfort",
        location: "Cairo, Egypt",
        type: "Single Room",
        pricePerNight: 85,
        capacity: 1,
        description: "Modern single room in the heart of Cairo near the Citadel.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-08", checkOut: "2025-11-11" },
            { checkIn: "2025-11-18", checkOut: "2025-11-21" },
        ],
        image: "https://picsum.photos/seed/room7/1024/764",
    },
    {
        id: 8,
        name: "Red Sea Paradise",
        location: "Sharm El Sheikh, Egypt",
        type: "Deluxe Suite",
        pricePerNight: 200,
        capacity: 3,
        description: "Luxury suite with private beach access and stunning sea views.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar", "Jacuzzi"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-25", checkOut: "2025-11-30" },
        ],
        image: "https://picsum.photos/seed/room8/1024/764",
    },
    {
        id: 9,
        name: "Aswan Serenity",
        location: "Aswan, Egypt",
        type: "Double Room",
        pricePerNight: 110,
        capacity: 2,
        description: "Peaceful double room with traditional Nubian design elements.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Balcony"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room9/1024/764",
    },
    {
        id: 10,
        name: "Khan El Khalili",
        location: "Cairo, Egypt",
        type: "Single Room",
        pricePerNight: 70,
        capacity: 1,
        description: "Budget-friendly room near the historic bazaar, perfect for explorers.",
        amenities: ["Free Wi-Fi", "Air Conditioning"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-13", checkOut: "2025-11-15" },
            { checkIn: "2025-11-28", checkOut: "2025-12-01" },
        ],
        image: "https://picsum.photos/seed/room10/1024/764",
    },
    {
        id: 11,
        name: "Pharaoh's Palace",
        location: "Luxor, Egypt",
        type: "Royal Suite",
        pricePerNight: 250,
        capacity: 4,
        description: "Opulent royal suite with Egyptian-themed decor and premium amenities.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar", "Jacuzzi", "Butler Service"],
        available: true,
        bookedDates: [
            { checkIn: "2025-12-05", checkOut: "2025-12-10" },
        ],
        image: "https://picsum.photos/seed/room11/1024/764",
    },
    {
        id: 12,
        name: "Coastal Comfort",
        location: "Marsa Alam, Egypt",
        type: "Double Room",
        pricePerNight: 100,
        capacity: 2,
        description: "Comfortable room with easy access to pristine beaches and coral reefs.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Pool Access"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room12/1024/764",
    },
    {
        id: 13,
        name: "Sphinx Suite",
        location: "Giza, Egypt",
        type: "Deluxe Suite",
        pricePerNight: 170,
        capacity: 2,
        description: "Elegant suite with panoramic views of the Sphinx and pyramids.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar", "Balcony"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-16", checkOut: "2025-11-20" },
            { checkIn: "2025-11-26", checkOut: "2025-11-29" },
            { checkIn: "2025-12-08", checkOut: "2025-12-12" },
        ],
        image: "https://picsum.photos/seed/room13/1024/764",
    },
    {
        id: 14,
        name: "Alexandria Pearl",
        location: "Alexandria, Egypt",
        type: "Single Room",
        pricePerNight: 78,
        capacity: 1,
        description: "Charming single room with Mediterranean influences and city views.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-19", checkOut: "2025-11-22" },
        ],
        image: "https://picsum.photos/seed/room14/1024/764",
    },
    {
        id: 15,
        name: "Dahab Hideaway",
        location: "Dahab, Egypt",
        type: "Double Room",
        pricePerNight: 90,
        capacity: 2,
        description: "Relaxed beach-style room perfect for diving enthusiasts.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Beach Access"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room15/1024/764",
    },
    {
        id: 16,
        name: "Cairo Central",
        location: "Cairo, Egypt",
        type: "Family Room",
        pricePerNight: 160,
        capacity: 4,
        description: "Central location family room with modern amenities and city views.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-09", checkOut: "2025-11-13" },
            { checkIn: "2025-11-24", checkOut: "2025-11-28" },
        ],
        image: "https://picsum.photos/seed/room16/1024/764",
    },
    {
        id: 17,
        name: "Siwa Dream",
        location: "Siwa Oasis, Egypt",
        type: "Single Room",
        pricePerNight: 65,
        capacity: 1,
        description: "Authentic desert experience with traditional architecture.",
        amenities: ["Free Wi-Fi", "Air Conditioning"],
        available: true,
        bookedDates: [
            { checkIn: "2025-12-02", checkOut: "2025-12-06" },
        ],
        image: "https://picsum.photos/seed/room17/1024/764",
    },
    {
        id: 18,
        name: "Hurghada Marina",
        location: "Hurghada, Egypt",
        type: "Deluxe Suite",
        pricePerNight: 185,
        capacity: 3,
        description: "Waterfront suite with marina views and luxury finishes.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar", "Balcony"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room18/1024/764",
    },
    {
        id: 19,
        name: "Valley Vista",
        location: "Luxor, Egypt",
        type: "Double Room",
        pricePerNight: 115,
        capacity: 2,
        description: "Room with views of the Valley of the Kings and West Bank.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Balcony", "Work Desk"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-11", checkOut: "2025-11-14" },
            { checkIn: "2025-11-21", checkOut: "2025-11-24" },
            { checkIn: "2025-12-03", checkOut: "2025-12-07" },
        ],
        image: "https://picsum.photos/seed/room19/1024/764",
    },
    {
        id: 20,
        name: "Port Said Porthole",
        location: "Port Said, Egypt",
        type: "Single Room",
        pricePerNight: 72,
        capacity: 1,
        description: "Nautical-themed room near the Suez Canal entrance.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Smart TV"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-17", checkOut: "2025-11-19" },
        ],
        image: "https://picsum.photos/seed/room20/1024/764",
    },
    {
        id: 21,
        name: "Zamalek Zen",
        location: "Cairo, Egypt",
        type: "Double Room",
        pricePerNight: 105,
        capacity: 2,
        description: "Peaceful room on Nile island with tree-lined streets nearby.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room21/1024/764",
    },
    {
        id: 22,
        name: "Coral Garden",
        location: "Sharm El Sheikh, Egypt",
        type: "Family Room",
        pricePerNight: 190,
        capacity: 4,
        description: "Family-friendly room with garden access and snorkeling nearby.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Pool Access", "Mini Bar"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-14", checkOut: "2025-11-18" },
            { checkIn: "2025-11-29", checkOut: "2025-12-03" },
        ],
        image: "https://picsum.photos/seed/room22/1024/764",
    },
    {
        id: 23,
        name: "Bibliotheca View",
        location: "Alexandria, Egypt",
        type: "Single Room",
        pricePerNight: 82,
        capacity: 1,
        description: "Modern room near the new Library of Alexandria with study area.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Work Desk"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-23", checkOut: "2025-11-26" },
        ],
        image: "https://picsum.photos/seed/room23/1024/764",
    },
    {
        id: 24,
        name: "Abu Simbel Sunrise",
        location: "Aswan, Egypt",
        type: "Deluxe Suite",
        pricePerNight: 165,
        capacity: 2,
        description: "Suite designed for early risers visiting Abu Simbel temples.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room24/1024/764",
    },
    {
        id: 25,
        name: "Coptic Corner",
        location: "Cairo, Egypt",
        type: "Double Room",
        pricePerNight: 98,
        capacity: 2,
        description: "Historic area room near ancient churches and synagogues.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Smart TV"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-07", checkOut: "2025-11-10" },
            { checkIn: "2025-11-27", checkOut: "2025-11-30" },
            { checkIn: "2025-12-04", checkOut: "2025-12-08" },
        ],
        image: "https://picsum.photos/seed/room25/1024/764",
    },
    {
        id: 26,
        name: "El Gouna Golf",
        location: "El Gouna, Egypt",
        type: "Deluxe Suite",
        pricePerNight: 195,
        capacity: 3,
        description: "Upscale suite with golf course and lagoon views.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Mini Bar", "Balcony"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-30", checkOut: "2025-12-04" },
        ],
        image: "https://picsum.photos/seed/room26/1024/764",
    },
    {
        id: 27,
        name: "Karnak Keeper",
        location: "Luxor, Egypt",
        type: "Single Room",
        pricePerNight: 88,
        capacity: 1,
        description: "Convenient room for exploring Karnak Temple complex.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Work Desk"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room27/1024/764",
    },
    {
        id: 28,
        name: "White Desert Wonder",
        location: "Farafra, Egypt",
        type: "Double Room",
        pricePerNight: 125,
        capacity: 2,
        description: "Unique desert lodge room with access to surreal white formations.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Desert Tours"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-12", checkOut: "2025-11-16" },
            { checkIn: "2025-12-01", checkOut: "2025-12-05" },
        ],
        image: "https://picsum.photos/seed/room28/1024/764",
    },
    {
        id: 29,
        name: "Taba Heights",
        location: "Taba, Egypt",
        type: "Family Room",
        pricePerNight: 175,
        capacity: 4,
        description: "Mountain and sea view family room at the Israeli border.",
        amenities: ["Free Wi-Fi", "Smart TV", "Air Conditioning", "Pool Access"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-20", checkOut: "2025-11-24" },
        ],
        image: "https://picsum.photos/seed/room29/1024/764",
    },
    {
        id: 30,
        name: "Garden City Gem",
        location: "Cairo, Egypt",
        type: "Single Room",
        pricePerNight: 76,
        capacity: 1,
        description: "Quiet room in diplomatic quarter with tree-lined streets.",
        amenities: ["Free Wi-Fi", "Air Conditioning"],
        available: false,
        bookedDates: [],
        image: "https://picsum.photos/seed/room30/1024/764",
    },
    {
        id: 31,
        name: "Ras Mohamed Reef",
        location: "Sharm El Sheikh, Egypt",
        type: "Double Room",
        pricePerNight: 130,
        capacity: 2,
        description: "Diver's paradise room near world-famous national park.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Diving Equipment Storage"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-15", checkOut: "2025-11-19" },
            { checkIn: "2025-11-25", checkOut: "2025-11-28" },
            { checkIn: "2025-12-06", checkOut: "2025-12-10" },
        ],
        image: "https://picsum.photos/seed/room31/1024/764",
    },
    {
        id: 32,
        name: "Felucca Float",
        location: "Aswan, Egypt",
        type: "Single Room",
        pricePerNight: 68,
        capacity: 1,
        description: "Riverside room perfect for traditional sailing boat trips.",
        amenities: ["Free Wi-Fi", "Air Conditioning", "River View"],
        available: true,
        bookedDates: [
            { checkIn: "2025-11-10", checkOut: "2025-11-13" },
        ],
        image: "https://picsum.photos/seed/room32/1024/764",
    },
];